config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'posts#index'

  resources :posts do
    member do
      put :status_new
      put :status_draft
      delete :delete_image
    end

    collection do
      get 'user_posts' => 'posts#user_posts', as: :user_posts
      get 'user_archive' => 'posts#user_archive', as: :user_archive
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

     if user.present?
      can %i[create user_posts user_archive], Post, user_id: user.id
      can :destroy, Post, user_id: user.id
      can :update, Post, user_id: user.id, status: 'draft'
      can :status_new, Post, user_id: user.id, status: 'draft'
      can :status_draft, Post, user_id: user.id, status: %w[rejected new_post archived]
    end
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user&.admin?
      can :access, :rails_admin
      can :read, :all
      can %i[destroy update approve], Post
      can %i[create destroy update], User
      can %i[create destroy], PostType
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_content, against: %i[title content],
  using: {
    tsearch: { prefix: true }
  }

  belongs_to :user, optional: true
  belongs_to :post_type, optional: true
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, :user_id, presence: true

  enum status: %i[draft new_post rejected approved published archived]

  scope :new_posts, -> { where(status: 'new_post') }
end

app/models/post_type.rb
class PostType < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do
    redirect_to main_app.root_path, notice: 'You have not permission to do this action'
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %i[show edit update destroy status_new status_draft]

  def index
    @q = Post.ransack(params[:q])
    if params[:query]
      @posts = Post.where(status: 'published').search_by_title_and_content(params[:query]).order(id: :desc).page(params[:page]).per(10)
    else
      @posts = @q.result.where(status: 'published').order(id: :desc).page(params[:page]).per(10)
    end
  end

  def new
    @post = Post.new
  end

  def show; end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save!
      redirect_to user_posts_posts_path, notice: 'Post created successfully'
    else
      flash.now[:alert] = 'Failed to create post'
      render :new
    end
  end

  def edit; end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: 'Post successfully deleted'
    else
      redirect_to posts_path, alert: 'Failed to delete post'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to request.referrer, notice: 'Post successfully edited'
    else
      flash.now[:alert] = 'Failed to edit post'
      render :edit
    end
  end

  def status_new
    @post.update_attributes status: 'new_post'
    redirect_to user_posts_posts_path, notice: 'Success! Post will be published after admin approval.'
  end

  def status_draft
    @post.update_attributes status: 'draft'
    redirect_to user_posts_posts_path, notice: 'Post was successfully converted to Draft Type.'
  end

  def user_posts
    @posts = current_user.posts.order(created_at: :desc).page(params[:page]).per(10)
  end

  def user_archive
    @posts = current_user.posts.where(status: 'archived').order(created_at: :desc).page(params[:page]).per(10)
  end

  def delete_image
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @image.purge
    redirect_to request.referrer, notice: 'Image deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :status, :post_type_id, images: [])
  end

  def set_post
    @post = Post.find(params[:id])
    @post = Post.with_attached_images.find(params[:id]) if @post.images.attached?
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_flash
    %w[notice alert]
      .select { |type| flash.key?(type) }
      .map { |type| flash_block(type) }
      .join.html_safe
  end

  private

  def flash_block(type)
    flash_classes = { notice: 'alert alert-success', alert: 'alert alert-danger' }
    content_tag(:div, class: flash_classes[type.to_sym]) do
      content_tag('button', 'x', class: 'close clear', 'data-dismiss' => 'alert') + flash[type.to_sym]
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title ADS
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.navbar.navbar-fixed-top.navbar-inverse
      .container
        = link_to "ADS", root_path, id: "logo"
        nav
          ul.nav.navbar-nav.navbar-right
            - if I18n.locale == :en
              li= link_to 'RU', locale: :ru
            - else I18n.locale == :ru
              li= link_to 'EN', locale: :en
            li= link_to t(:posts), posts_path
            -if current_user && current_user.admin
              li= link_to t(:nav_admin_panel), rails_admin.dashboard_path
            -elsif current_user && !current_user.admin
              li= link_to t(:my_posts), user_posts_posts_path
              li= link_to t(:archive), user_archive_posts_path
              li= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path
              li= link_to t(:sign_out), destroy_user_session_path, method: :delete
            -else
              li= link_to t(:sign_up), new_user_registration_path 
              li= link_to t(:sign_in), new_user_session_path
    .container
      = render_flash
      = yield

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.input :title,
    label: t(:title)
  = f.input :content,
    label: t(:description)
  = f.file_field :images, multiple: true
  -if @post.images.attached?
    table.table.table-sm.table-bordered[style="margin-top: 20px"]
      thead
        tr
          th.text-center
            = t(:images)
          th.text-center
            = t(:actions)
      tbody
        - @post.images.each do |image|
          tr
            td.text-center
              = image_tag image.variant(resize_to_limit: [100, 100])

  = f.button :submit, t(:save), class: 'btn btn-primary'
  = link_to t(:cancel), posts_path, class: 'btn btn-default'

app/views/posts/_post.html.slim
table.table.table-striped
  thead
    tr
      th
      th = t(:title)
      th = t(:description)
      th = t(:creator)
      -if current_user
        th = t(:status)
  tbody
    - @posts.each do |post|
      tr
        -if can? :destroy, post
          td
            .btn-group-vertical role="group"
              -if can? :status_new, post
                = link_to [:status_new, post], class: 'btn btn-success btn-sm', method: :put do
                  span.glyphicon.glyphicon-check aria-hidden="true"
              -if can? :status_draft, post
                = link_to [:status_draft, post], class: 'btn btn-success btn-sm', method: :put do
                  span.glyphicon.glyphicon-chevron-left aria-hidden="true"
              -if can? :edit, post    
                = link_to [:edit, post], class: 'btn btn-primary btn-sm' do
                  span.glyphicon.glyphicon-pencil aria-hidden="true" 
              = link_to [post], class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: t(:are_you_sure) } do
                span.glyphicon.glyphicon-trash aria-hidden="true"
        -else 
          td
        td
          = link_to t("#{post.title}"), post
        td= post.content
        td= "#{User.find(post.user_id).first_name} #{User.find(post.user_id).last_name}"
        -if current_user
          td= post.status

= paginate @posts, theme: 'twitter-bootstrap-3'          

app/views/posts/_search_form.html.slim
.col-md-6
  .text-left[style="margin-top: 20px"]
    = form_tag(posts_path, method: "get", remote: true, class: 'form-inline') do
      = label_tag(:search, t(:search))
      = text_field_tag :query, params[:query], label: t(:search), class: 'form-control'
      = submit_tag t(:search), class: 'btn btn-sm btn-success'
.row
  = search_form_for @q, remote: true, builder: SimpleForm::FormBuilder, wrapper: :horizontal_form, class: 'form-horizontal' do |f|
    .col-md-6
      = f.input :user_id_eq, collection: User.all.where(admin: false).map{ |t| ["#{t.first_name} #{t.last_name}", t.id] }, required: false, label: t(:creator)
    .col-md-6
      = f.input :post_type_id_eq, collection: PostType.all.map{ |t| [t.name, t.id] }, required: false, label: t(:type)
      = f.button :submit, t(:filter_submit), class: 'btn btn-primary pull-right'

app/views/posts/edit.html.slim
.row
  .col-sm-offset-4.col-sm-4
    h3 = t(:edit)

    = render 'form'	

app/views/posts/index.html.slim
h3 = t(:posts)

.row
  -if current_user && !current_user.admin
    = link_to t(:add_post), new_post_path, class: 'btn btn-success pull-right'

.row
  '  '    

= render 'search_form'

#search-posts
  = render 'post'

app/views/posts/index.js.erb
$("#search-posts").html("<%= escape_javascript(render :partial => 'post') %>");

app/views/posts/new.html.slim
h3 = t(:new_post)

=render 'form'

app/views/posts/show.html.slim
.center.jumbotron
  h1 #{@post.title}
  h2 #{@post.content}
  -if @post.images.attached?
    -@post.images.each do |image|
      = image_tag image.variant(resize: "300x300")

  h3
   -if can? :edit, @post
       = link_to t(:edit), edit_post_path, class: 'btn btn-primary'

app/views/posts/user_archive.html.slim
h3 = t(:archive)

= link_to t(:add_post), new_post_path, class: 'btn btn-success pull-right'

= render 'post'

app/views/posts/user_posts.html.slim
h3 = t(:my_posts)

= link_to t(:add_post), new_post_path, class: 'btn btn-success pull-right'

= render 'post'